apiVersion: apps/v1
kind: Deployment
metadata:

  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-simulator
  template:
    metadata:
      labels:
        app: data-simulator

    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: simulator
          image: ghcr.io/asign796/axion-data-simulator:5e43f4d
          env:
            - name: API_URL
              value: "http://10.96.191.100:8000/api/v1/telemetry/ingest"
            - name: INTERVAL_SECONDS
              value: "5"
          ports:
            - containerPort: 8080